CREATE TABLE `dotloop_integrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accessToken` text NOT NULL,
	`refreshToken` text,
	`expiresAt` timestamp,
	`profileId` varchar(255),
	`lastSyncAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dotloop_integrations_id` PRIMARY KEY(`id`),
	CONSTRAINT `dotloop_integrations_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`uploadId` int NOT NULL,
	`userId` int NOT NULL,
	`loopId` varchar(255),
	`loopViewUrl` text,
	`loopName` varchar(500),
	`loopStatus` varchar(100),
	`createdDate` varchar(50),
	`closingDate` varchar(50),
	`listingDate` varchar(50),
	`offerDate` varchar(50),
	`address` text,
	`price` int,
	`propertyType` varchar(100),
	`bedrooms` int,
	`bathrooms` int,
	`squareFootage` int,
	`city` varchar(100),
	`state` varchar(50),
	`county` varchar(100),
	`leadSource` varchar(100),
	`agents` text,
	`createdBy` varchar(255),
	`earnestMoney` int,
	`salePrice` int,
	`commissionRate` int,
	`commissionTotal` int,
	`buySideCommission` int,
	`sellSideCommission` int,
	`companyDollar` int,
	`referralSource` varchar(255),
	`referralPercentage` int,
	`complianceStatus` varchar(100),
	`tags` text,
	`originalPrice` int,
	`yearBuilt` int,
	`lotSize` int,
	`subdivision` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `transactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `uploads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`recordCount` int NOT NULL,
	`uploadedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `uploads_id` PRIMARY KEY(`id`)
);
