ALTER TABLE `agent_assignments` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `audit_logs` MODIFY COLUMN `createdAt` timestamp(3) NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `brokerage_branding` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `cda_documents` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `cda_field_mappings` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `cda_generated` MODIFY COLUMN `generatedAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `cda_templates` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `commission_calculations` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `commission_plans` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `oauth_tokens` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `platform_admin_logs` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `prospect_activity` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `recruiting_import_history` MODIFY COLUMN `importedAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `recruiting_pipeline_activity` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `recruiting_prospects` MODIFY COLUMN `importedAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `recruiting_retention_risk` MODIFY COLUMN `lastCalculated` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `retention_alerts` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `teams` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `tenant_members` MODIFY COLUMN `joinedAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `tenant_members` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `tenants` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `tier_history` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `token_audit_logs` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `transactions` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `upload_activity_log` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `upload_sharing` MODIFY COLUMN `sharedAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `upload_snapshots` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `uploads` MODIFY COLUMN `uploadedAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `user_team_members` MODIFY COLUMN `addedAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `user_teams` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `lastSignedIn` timestamp NOT NULL DEFAULT (now());